name: Deploy AWS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clone do projeto
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: "ezambomsantana"
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ezambomsantana/movimentacoes-ci:${{ github.sha }}

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_TEST }}
          username: "ubuntu"
          key: ${{ secrets.KEY_TEST }}
          port: 22
          script: |
            docker stop movimentacoes || true
            docker rm --force movimentacoes || true
            docker run -d -p 8081:5000 \
              --name movimentacoes \
              ezambomsantana/movimentacoes-ci:${{ github.sha }}